### ISSUE TITLE
Add <br /> tags for user interface

### ISSUE THREAD

**Issue by aleksijuvani** [aleksijuvani/polygonist#177]
* [ ] `::before` and `::after` pseudo-elements
* [ ] `content` property (we only need strings and support `\A` for linebreaks
* [ ] add the following to the base style
```css
br::before
{
	content: "\A";
	white-space: pre-line;
}
```
